### ISSUE TITLE
Ontology dependencies

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/sbol_factory#11]
I'm not finding a way to have an SBOL-factory ontology depend on another SBOL-factory ontology right now, which I need to do for PAML.

I see that in query.py, the set of ontology dependencies appears to be hardwired, rather than actually reading the list from the ontology file declaration.

**Comment by bbartley** [comment]
I believe the following should work.  Inside the \_\_init\_\_.py:
```
__factory__ = SBOLFactory(locals(),  os.path.join(os.path.dirname(os.path.realpath(__file__)), 'base_ontology.ttl')
__factory__ = SBOLFactory(locals(),  os.path.join(os.path.dirname(os.path.realpath(__file__)), 'dependent_ontology.ttl')
```

Alternatively, you could put each ontology in separate packages:

base_ontology/\_\_init\_\_.py:
```
__factory__ = SBOLFactory(locals(),  os.path.join(os.path.dirname(os.path.realpath(__file__)), 'base_ontology.ttl'),
```

dependent_ontology/\_\_init\_\_.py
```
__factory__ = SBOLFactory(locals(),  os.path.join(os.path.dirname(os.path.realpath(__file__)), 'dependent_ontology.ttl'),
```

Then, in your client script:
```
import base_ontology
import dependent_ontology
```

**Comment by jakebeal** [comment]
I have tried both of these patterns --- they fail during the loading of the dependent ontology with a missing superclass error, since the superclass is in the base ontology and that isn't available during the build process

Declaration:
```
paml:Protocol rdf:type owl:Class ;
              rdfs:comment "A protocol is an activity in the laboratory" ;
        rdfs:subClassOf uml:Activity .
```

Error:
```
  File "/Users/jakebeal/projects/SD2/PAML/paml/__init__.py", line 8, in <module>
    __factory__ = SBOLFactory(locals(),
  File "/usr/local/lib/python3.9/site-packages/sbol_factory/sbol_factory.py", line 66, in __init__
    docstring += self.generate(class_uri)
  File "/usr/local/lib/python3.9/site-packages/sbol_factory/sbol_factory.py", line 74, in generate
    superclass_uri = SBOLFactory.query.query_superclass(class_uri)
  File "/usr/local/lib/python3.9/site-packages/sbol_factory/query.py", line 81, in query_superclass
    raise Exception('{} has no superclass'.format(subclass))
Exception: http://bioprotocols.org/paml#Protocol has no superclass
```

**Comment by bbartley** [comment]
At the base level of your ontologies, you have to inherit from a class that's defined in the pySBOL3 library.  So, either uml:Activity or paml:Protocol need to be subclassed from sbol:TopLevel.

I don't think multiple inheritance is currently supported, though previously some tests Tom and I did established that it will work in principle.

**Comment by jakebeal** [comment]
Yes, uml:Activity is subclassed from sbol:TopLevel, and I have no problem building uml:Activity objects.
But when paml is being constructed, it appears that the constructor isn't being able to find the definition of uml:Activity.
I think this is due to the hard-wiring in the `Query.__init__` function: https://github.com/SynBioDex/sbol_factory/blob/2f09b19ce543d5bb4d28f1ce50d061b7cf3dbb09/sbol_factory/query.py#L17

**Comment by bbartley** [comment]
This was caused because the different SBOLFactory instances use separate graphs.  Thus, it was not possible to infer  relationships between the two ontologies.  #13  creates a static attribute on the SBOLFactory class that contains a graph.  All SBOLFactory instances will share this graph.
