### ISSUE TITLE
Validate OWL

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/sbol_factory#26]
Input ontologies should be validated to make sure they are valid OWL

**Comment by jakebeal** [comment]
Linked to:
- https://github.com/SD2E/paml/pull/41
- https://github.com/SD2E/paml/issues/30

**Comment by jakebeal** [comment]
... and this isn't actually an issue for sbol_factory, since by the time it encounters the file, it's reading it in and will discover validation problems the hard way.
