### ISSUE TITLE
1.0a7 release needs a corresponding release on GitHub

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/sbol_factory#38]
The 1.0a7 release on pypi (https://pypi.org/project/sbol-factory/1.0a7/) doesn't have a corresponding tag and release here on GitHub. Can you please add one with a description of the changes that are part of this release?

**Comment by bbartley** [comment]
Added https://github.com/SynBioDex/sbol_factory/releases/tag/v1.0a7
