### ISSUE TITLE
Upgrade to pySBOL3-1.0b6

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/sbol_factory#39]
The pySBOL3-1.0b6 release is now out and upgrades its rdflib dependency to 6.0, which is incompatible with sbol_factory's requirement for rdflib version 5.0

**Comment by jakebeal** [comment]
Note that resolution of this issue should wait until resolution of https://github.com/SynBioDex/pySBOL3/issues/307

**Comment by jakebeal** [comment]
Issue is resolved, just needs the 1.0b7 release to go out from pySBOL3. @tcmitchell : when is that scheduled?

**Comment by jakebeal** [comment]
Let's push synbiodex/pysbol3#176 back to 1.0b8 and get 1.0b7 out now, then, so that we can unpin dependencies and roll forward again.

**Comment by tcmitchell** [comment]
sbol3 1.0b7 has been released and is available now.
