### ISSUE TITLE
Reuse identical graphics

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/sbol_factory#46]
Sibling and child classes in hierarchies share the same graphic. Rather than repeating the graphic, it would be good to consolidate it to the root class and have them all point to the same one.

A good cut-point for this would be on the lines of clusters (#45)

**Comment by bbartley** [comment]
First, can you confirm that this is actually the behavior we desire?  By point of comparison, I don't think the SBOL spec reuses identical diagrams for different classes.  For example, I don't think sibling classes share the same diagram.  The identical graphics are an artifact of how UMLFactory is currently configured, which could be tweaked to produce diagrams more consistent with conventions used in the SBOL spec.

**Comment by jakebeal** [comment]
This is how the SBOL specification works for anything that has subclasses besides Identified and Toplevel - there just aren't many cases of that in SBOL vs. in UML and PAML.
In the SBOL3 spec it is handled this way for:
- Feature (Figure 9)
- Location (Figure 10)
which are the only two non-root classes with subclasses
