### ISSUE TITLE
Develop branch should have its version advanced

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/sbol_factory#52]
When I'm installing sbol_factory off of a branch right now, it's coming across as version 1.0a8; per GitFlow this should be advanced on a develop branch to a pre-release 1.0a9

**Comment by bbartley** [comment]
Following @tcmitchell's example, I will bump the version on master after tagging a new release.  Resolved in b2ca5d0f821c61eb9cd2446ae3af724dee4b0999
