### ISSUE TITLE
SBOLFactory shouldn't print class information by default

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/sbol_factory#55]
Building an SBOLFactory package generates a whole bunch of print material, e.g.

````
Dependency
--------
	objects	TopLevel	0	inf
	module	Module	0	1
	package	Package	1	1
	includeObjectReferences	boolean	0	1
````

This information is noisy for normal operation an should only show up if a debugging option is turned on

**Comment by jakebeal** [comment]
In fact, it looks like this is only supposed to come up when Verbose is true, but that option isn't being respect in my copy of 1.0a9

**Comment by jakebeal** [comment]
@bbartley Can we please get a release cut that includes this fix in it?

**Comment by bbartley** [comment]
https://github.com/SynBioDex/sbol_factory/releases/tag/v1.0a10
