### ISSUE TITLE
Add build matrix to github workflow

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/sbol_factory#63]
Run tests across multiple platforms/python versions

**Comment by jakebeal** [comment]
Blocker on https://github.com/SynBioDex/SBOL-utilities/pull/88
Thus, fix should be released before 1.0 as another alpha

**Comment by bbartley** [comment]
Added matrix for Python 3.7-3.10 and Mac and Windows systems in ab67c13f43d98421274a52c4ce01aebd15020135
