### ISSUE TITLE
Confirm that improved ontology files work with SBOL factory

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/sbol_factory#64]
When https://github.com/Bioprotocols/paml/pull/68 is ready to merge, need to make sure that the updated ontology files are compatible with SBOL factory.

**Comment by bbartley** [comment]
Confirmed that SBOLFactory has no problem interpreting Restrictions in the cleaned-up ontologies, see https://github.com/Bioprotocols/paml/pull/68
